### PR TITLE
Added auth pages

### PR DESCRIPTION
**Pull request by srishti-maurya**
Added auth pages
- Login
- Signup
- Logout

Note: Responsiveness not is added yet

Live links:

- https://deploy-preview-4--plan-it-shop-it.netlify.app/pages/authentication/login
- https://deploy-preview-4--plan-it-shop-it.netlify.app/pages/authentication/signup
- https://deploy-preview-4--plan-it-shop-it.netlify.app/pages/authentication/logout

Screenshot 2022-02-12 at 10 44 14 PM
screencapture-127-0-0-1-5500-pages-Authentication-Login-html-2022-02-12-22_42_56

screencapture-127-0-0-1-5500-pages-Authentication-SignUp-html-2022-02-12-22_43_02

### CODE REVIEW

**Review by Chakravarthi0 — APPROVED** [review]
looks good to me

**Review by MarkVed17 — APPROVED** [review]
Looks good! You may proceed 👍🏼

**Review by KaustubhM1997 — APPROVED** [review]
looks good!

**Review by tanveertkd — APPROVED** [review]
Good to go! 👍

**Comment by tanveertkd** [comment]
Just one suggestion, your footer gets shifted up from the bottom of the page to right below the login/signup modal. You might want to fix that.

**Pull request merged**
